# Generated by Django 3.2.13 on 2023-11-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('address', models.CharField(max_length=45)),
                ('day', models.CharField(default='Monday', max_length=15)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_project.region')),
            ],
        ),
    ]
